name: license-headers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check SPDX headers in Rust sources
        shell: bash
        run: |
          set -euo pipefail
          missing=$(git ls-files "**/*.rs" | xargs -I{} sh -c 'grep -q "SPDX-License-Identifier: MIT" "{}" || echo {}' || true)
          if [ -n "$missing" ]; then
            echo "Missing SPDX in:" >&2
            echo "$missing" >&2
            exit 1
          fi


